### PR TITLE
Match the docs and explain list_token_error

### PR DESCRIPTION
**Pull request by jayson-jensen-pro**
@a-u-h-g If the list_token_error section looks good I'll copy that over to the graph-google repo as well.

### CODE REVIEW

**Comment by erkangz** [comment]
Are these changes also made to the graph-Google repo?

**Comment by erkangz** [comment]
fyi, there's this too https://github.com/JupiterOne/docs/pull/155

**Comment by a-u-h-g** [comment]
I sync'd up with Jayson on order of operations (this was meant to be a draft) - somehow missed your other PR - thanks for linking. Will merge that soon and we'll make sure everything is reflected accurately.

**Comment by jayson-jensen-pro** [comment]
I created a PR in the graph-google repo, will convert this draft to ready for review once merged  [#95](https://github.com/JupiterOne/graph-google/pull/95)

**Review by erkangz — APPROVED** [review]

**Review by a-u-h-g — APPROVED** [review]

**Pull request merged**
