### PR TITLE
update veracode docs

### PR DESCRIPTION
**Pull request by mdaum**
Needed to delete and re-update integrations to get the new contents of veracode docs into this repo.

### CODE REVIEW

**Comment by mdaum** [comment]
@janettelynch some formatting was done via [format.js](https://github.com/JupiterOne/docs/blob/vanilla-staging/packages/integrations-handling/src/format.js) as a result of running `yarn updateIntegrations` in project root. If there are additional rules we would like to try and enforce across our integrations docs, we should look into possibly modifying this code.

**Comment by janettelynch** [comment]
@mdaum Thanks for doing this. I have tried updating the integrations template to get some universal changes done across the board. I'll dig up that PR.

**Comment by mdaum** [comment]
@janettelynch yes, but it should be applied in the [graph-veracode](https://github.com/JupiterOne/graph-veracode/blob/main/docs/jupiterone.md) project that this repo is copying over docs from. Otherwise the contents will get overwritten on next integrations update (which happens nightly i believe).
this is the [commit](https://github.com/JupiterOne/docs/commit/e5a212615009af0b472cc45a442c60065c031d12) where the changes were made. This can't easily be applied across repos. But it can be applied to this branch to get the desired output file, and then we can copy it over to the graph project. I will take 15 mins to give this a shot today.

**Comment by mdaum** [comment]
@janettelynch I have patched your changes from the closed PR, copied over to [graph-veracode](https://github.com/JupiterOne/graph-veracode/blob/main/docs/jupiterone.md) project, and re-imported. This PR is ready for review.

**Review by aiwilliams — APPROVED** [review]

**Pull request merged**
